title: Greenwich IT Service Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://luminous-malasada-fa9168.netlify.app/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems: []
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo_final_on_white.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: IT
      link: https://www.gre.ac.uk/it-and-library
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: General IT Services
    - name: IT Networks
    - name: Staff IT Services
    - name: Student IT Services
    - name: Teaching & Learning
    - name: University Library Services
  description: "This site displays information about the availability of IT
    services at the University of Greenwich. Issues will appear as a coloured
    box below this header: Click on the boxes to find out more information."
  enableCustomHTML: true
  useLargeHeaderDesign: false
